projects:
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4444/graphql
  database:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml